# Generated by Django 4.0.4 on 2022-06-07 07:45

import core.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_shopuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/default-user.png', null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'avatar_images'}), verbose_name='Avatar'),
        ),
    ]
