# Generated by Django 4.0.4 on 2022-06-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0041_remove_pagesection_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='accounts_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable account features, like login, signup, or profile page.', verbose_name='Account Features Enabled'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='core.pagesection'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.pagesection'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='settings',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.contactsettings'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.pagesection'),
        ),
    ]
