# Generated by Django 4.0.4 on 2022-06-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.RemoveField(
            model_name='frequentlyaskedquestion',
            name='ordering',
        ),
    ]
