# Generated by Django 4.0.4 on 2022-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_controlcenter_accounts_enabled_alter_counter_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='menu_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Menu Order'),
        ),
    ]
