# Generated by Django 4.0.4 on 2022-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='show_footer_waves',
            field=models.BooleanField(default=True, verbose_name='Show Footer Waves'),
        ),
    ]
