# Generated by Django 4.0.4 on 2022-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_frequentlyaskedquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
