# Generated by Django 4.0.4 on 2022-06-03 20:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagesection_created_by_pagesection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesectionplacement',
            options={'ordering': ['sort_order'], 'verbose_name': 'Page Sections', 'verbose_name_plural': 'Page Sections'},
        ),
        migrations.AlterField(
            model_name='homepagesectionplacement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='core.homepage'),
        ),
    ]
