# Generated by Django 4.0.4 on 2022-06-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_homepagesectionplacement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.button', verbose_name='Button'),
        ),
    ]
