# Generated by Django 4.0.4 on 2022-06-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_frequentlyaskedquestion_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'ordering': ['sort_order'], 'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
    ]
