# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagesection_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='cta_button',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='second_section_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='second_section_text_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='second_section_text_en',
        ),
    ]
