# Generated by Django 4.0.4 on 2022-06-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_frequentlyaskedquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'ordering': ['order'], 'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='sort_order',
            new_name='order',
        ),
    ]
