# Generated by Django 4.1.1 on 2022-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='gdpr_url',
            field=models.URLField(blank=True, null=True, verbose_name='GDPR URL'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='terms_and_conditions_url',
            field=models.URLField(blank=True, null=True, verbose_name='Terms And Conditions URL'),
        ),
    ]
