# Generated by Django 4.0.4 on 2022-06-03 21:04

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_siteconfiguration_cta_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#0e0e0e', max_length=7),
        ),
    ]
