# Generated by Django 4.0.4 on 2022-06-22 20:34

import core.models.fonts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_googlefontsubset_googlefontvariant_googlefont'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='google_font',
            field=models.ForeignKey(default=core.models.fonts.get_default_font_id, on_delete=models.SET(core.models.fonts.get_default_font), to='core.googlefont'),
        ),
        migrations.AlterField(
            model_name='googlefont',
            name='version',
            field=models.CharField(default='v1', max_length=16, verbose_name='Font Version'),
        ),
    ]
