# Generated by Django 4.1.1 on 2022-11-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testimonial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contact Address'),
        ),
    ]
