# Generated by Django 4.0.4 on 2022-06-22 20:42

import core.models.fonts
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_brandsettings_google_font_alter_googlefont_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='google_font',
            field=modelcluster.fields.ParentalKey(default=core.models.fonts.get_default_font_id, on_delete=models.SET(core.models.fonts.get_default_font), related_name='google_font', to='core.googlefont'),
        ),
    ]
