# Generated by Django 4.0.4 on 2022-06-15 15:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('core', '0007_alter_frequentlyaskedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('default_section', 'Default Section'), ('faq_section', 'FAQ Section'), ('contact_section', 'Contact Section'), ('product_list_square', 'Product List (Square Cards)'), ('product_list_tall', 'Product List (Tall Cards)')], default='default_section', max_length=125, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ProductPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='core.pagesection')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
