# Generated by Django 4.0.4 on 2022-06-15 16:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pagesection_section_type_productplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplacement',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.pagesection'),
        ),
    ]
