# Generated by Django 4.0.4 on 2022-06-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0008_simplepage_alter_homepagesectionplacement_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageSectionPlacement',
            new_name='PageSectionPlacement',
        ),
    ]
