# Generated by Django 4.0.4 on 2022-06-22 20:47

import core.models.fonts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_brandsettings_google_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='google_font',
            field=models.ForeignKey(default=core.models.fonts.get_default_font_id, on_delete=models.SET(core.models.fonts.get_default_font), to='core.googlefont'),
        ),
    ]
