# Generated by Django 4.0.4 on 2022-06-04 19:04

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import functools
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_rename_homepagesectionplacement_pagesectionplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheading_text',
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='SNAPSHOP', help_text='This is the big title that shows up in the hero section.', max_length=64, verbose_name='Hero Title')),
                ('subheading', models.CharField(blank=True, default='', help_text='This is the text that shows up under the title in the hero section.', max_length=128, verbose_name='Hero Subheading')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'hero_images'}), verbose_name='Hero Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'hero_videos'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Hero Video')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.herosection', verbose_name='Hero Section'),
        ),
    ]
