# Generated by Django 4.0.4 on 2022-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_productplacement_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('default_section', 'Default Section'), ('faq_section', 'FAQ Section'), ('contact_section', 'Contact Section'), ('counters_section', 'Counters Section'), ('testimonials_section', 'Testimonials Section'), ('product_list_square', 'Product List (Square Cards)'), ('product_list_tall', 'Product List (Tall Cards)')], default='default_section', max_length=125, verbose_name='Type'),
        ),
    ]
