# Generated by Django 4.0.4 on 2022-06-24 12:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('core', '0009_alter_brandsettings_google_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Twitter', max_length=64, verbose_name='Name')),
                ('url', models.URLField(help_text='E.g. https://twitter.com/home/', max_length=512, verbose_name='URL')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon')),
            ],
        ),
        migrations.AlterModelOptions(
            name='googlefont',
            options={'ordering': ('family',)},
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='trip_advisor',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='youtube',
        ),
        migrations.CreateModel(
            name='SocialLinkPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.contactsettings')),
                ('social_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.sociallink')),
            ],
            options={
                'verbose_name': 'Social Links',
                'verbose_name_plural': 'Social Links',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
