# Generated by Django 4.0.4 on 2022-06-04 19:55

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text Color'),
        ),
    ]
