# Generated by Django 4.0.4 on 2022-06-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_testimonial_options_remove_testimonial_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Counter', 'verbose_name_plural': 'Counters'},
        ),
        migrations.RemoveField(
            model_name='counter',
            name='ordering',
        ),
    ]
