# Generated by Django 4.0.4 on 2022-06-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialmediasettings_colorsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorsettings',
            options={'verbose_name': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social Media'},
        ),
    ]
