# Generated by Django 4.0.4 on 2022-06-04 23:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0013_alter_colorsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('primary_color', wagtail_color_panel.fields.ColorField(max_length=7, verbose_name='Primary Color')),
                ('accent_color', wagtail_color_panel.fields.ColorField(max_length=7, verbose_name='Accent Color')),
                ('text_color', wagtail_color_panel.fields.ColorField(max_length=7, verbose_name='Text Color')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Branding',
            },
        ),
        migrations.DeleteModel(
            name='ColorSettings',
        ),
    ]
