# Generated by Django 4.0.4 on 2022-06-04 23:26

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_brandsettings_delete_colorsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='accent_color',
            field=wagtail_color_panel.fields.ColorField(default='#4E8397', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='primary_color',
            field=wagtail_color_panel.fields.ColorField(default='#4E8397', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='text_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7, verbose_name='Text Color'),
        ),
    ]
