# Generated by Django 4.0.4 on 2022-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_brandsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
