# Generated by Django 4.0.4 on 2022-06-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pagesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='This image will show up on the right side of the section.', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
