# Generated by Django 4.0.4 on 2022-06-24 14:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_homepage_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['sort_order'], 'verbose_name': 'Social Links', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='settings',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.contactsettings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='SocialLinkPlacement',
        ),
    ]
