# Generated by Django 4.0.4 on 2022-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sociallink_options_sociallink_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
