# Generated by Django 4.0.4 on 2022-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sociallink_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='enable_particles',
            field=models.BooleanField(default=False, verbose_name='Enable Particles'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('default_section', 'Default Section'), ('faq_section', 'FAQ Section'), ('contact_section', 'Contact Section'), ('counters_section', 'Counters Section'), ('testimonials_section', 'Testimonials Section'), ('product_carousel_section', 'Product Carousel Section'), ('product_list_square', 'Product List (Square Cards)'), ('product_list_tall', 'Product List (Tall Cards)'), ('checkout_section', 'Checkout Section')], default='default_section', max_length=125, verbose_name='Type'),
        ),
    ]
