# Generated by Django 4.0.4 on 2022-06-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('core', '0019_alter_herosection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ForeignKey(blank=True, help_text='This image shows up in the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Image'),
        ),
    ]
