# Generated by Django 4.0.4 on 2022-06-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('core', '0020_herosection_enable_particles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='footer_image',
            field=models.ForeignKey(blank=True, help_text='This image shows up in the footer section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Image'),
        ),
    ]
