# Generated by Django 4.0.4 on 2022-06-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_herosection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_me_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_me_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quiz_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quiz_subheading',
        ),
    ]
