# Generated by Django 4.0.4 on 2022-06-26 08:07

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_brandsettings_footer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='error_color',
            field=wagtail_color_panel.fields.ColorField(default='#761C19', help_text='The color of error messages in forms.', max_length=7, verbose_name='Error Color'),
        ),
    ]
