# Generated by Django 4.0.4 on 2022-06-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('core', '0021_remove_homepage_about_me_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_me_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_me_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_me_text_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_me_text_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='ebook_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='ebook_text_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='ebook_text_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_heading',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_heading_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_heading_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_subheading',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_subheading_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quiz_subheading_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='subheading_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='subheading_text_cs',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='subheading_text_en',
        ),
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Image'),
        ),
    ]
