# Generated by Django 4.0.4 on 2022-06-26 20:58

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_brandsettings_error_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='cart_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7, verbose_name='Cart Color'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='cart_text_color',
            field=wagtail_color_panel.fields.ColorField(default='#121212', max_length=7, verbose_name='Cart Text Color'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='accent_color',
            field=wagtail_color_panel.fields.ColorField(default='#131313', max_length=7, verbose_name='Accent Color'),
        ),
    ]
