# Generated by Django 4.0.4 on 2022-06-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_shopsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopsettings',
            options={'verbose_name': 'Shop Settings'},
        ),
    ]
