# Generated by Django 4.0.4 on 2022-06-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0025_remove_pagesection_button_remove_pagesection_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicpagesection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contactsection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='pagesection',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
