# Generated by Django 4.0.4 on 2022-06-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0026_alter_basicpagesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='Snap Shop', max_length=64, verbose_name='Full Name')),
                ('vat_id', models.CharField(blank=True, default='', max_length=10, verbose_name='VAT ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(help_text='Your Facebook page URL')),
                ('instagram', models.URLField(help_text='Your Instagram Profile URL')),
                ('linkedin', models.CharField(help_text='Your Instagram username, without the @', max_length=255)),
                ('trip_advisor', models.URLField(help_text='Your Trip Advisor page URL')),
                ('youtube', models.URLField(help_text='Your YouTube channel or user account URL')),
                ('tiktok', models.URLField(help_text='Your TikTok account URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media',
            },
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
