# Generated by Django 4.0.4 on 2022-06-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_shopsettings_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopSettings',
        ),
    ]
