# Generated by Django 4.0.4 on 2022-06-27 09:35

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_shopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color'),
        ),
    ]
