# Generated by Django 4.0.4 on 2022-06-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contactsettings_delete_socialmediasettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Contact'},
        ),
    ]
