# Generated by Django 4.0.4 on 2022-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_contactsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='linkedin',
            field=models.URLField(help_text='Your LinkedIn Profile URL'),
        ),
    ]
