# Generated by Django 4.0.4 on 2022-06-27 09:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopsettings'),
        ('core', '0028_button_text_color_alter_button_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypePlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('split_into_categories', models.BooleanField(default=True, help_text='Split the displayed products into categories.', verbose_name='Split Into Categories')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.producttype')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='core.pagesection')),
            ],
            options={
                'verbose_name': 'Product Types',
                'verbose_name_plural': 'Product Types',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
