# Generated by Django 4.0.4 on 2022-06-28 12:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_producttypeplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['sort_order'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='section',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.pagesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Author'),
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='translation_key',
        ),
    ]
