# Generated by Django 4.0.4 on 2022-06-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
