# Generated by Django 4.0.4 on 2022-06-28 16:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_ebook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='counter',
            name='section',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='core.pagesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='counter',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='translation_key',
        ),
    ]
