# Generated by Django 4.0.4 on 2022-06-28 16:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_counter_unique_together_counter_section_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frequentlyaskedquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='section',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.pagesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='frequentlyaskedquestion',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='frequentlyaskedquestion',
            name='translation_key',
        ),
    ]
