# Generated by Django 4.0.4 on 2022-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_frequentlyaskedquestion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='full_name',
            field=models.CharField(blank=True, default='Store Engine', max_length=128, verbose_name='Full Name'),
        ),
    ]
