# Generated by Django 4.0.4 on 2022-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_contactsettings_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='business_title',
            field=models.CharField(blank=True, default='Eshop Platform', help_text='E.g. "Personal Coach"', max_length=64, null=True, verbose_name='Business Title'),
        ),
    ]
