# Generated by Django 4.0.4 on 2022-06-28 17:52

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_brandsettings_logo_controlcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='notification_bar_color',
            field=wagtail_color_panel.fields.ColorField(default='#C26F5E', max_length=7, verbose_name='Notification Bar Color'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='notification_bar_text_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7, verbose_name='Notification Bar Text Color'),
        ),
    ]
