# Generated by Django 4.0.4 on 2022-06-30 16:40

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0038_brandsettings_notification_bar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_page_sections', to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
