# Generated by Django 4.0.4 on 2022-06-30 16:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0039_pagesection_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_page_sections', to='wagtailcore.page'),
        ),
    ]
