# Generated by Django 4.0.4 on 2022-06-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_pagesection_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='page',
        ),
    ]
