version: "3"
services:
  app:
    restart: always
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storengine
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: storengine.settings.settings
      DJANGO_DEBUG: "True"
      DEBUG: "True"
      ENV: "LOCAL"
      BASE_URL: "http://localhost:8000"
    privileged: true

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=storengine
      - POSTGRES_USER=storengine
      - POSTGRES_PASSWORD=storengine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
