# Generated by Django 4.0.4 on 2022-06-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mails', '0001_initial'),
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaction',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.email'),
        ),
    ]
