# Generated by Django 4.0.4 on 2022-07-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_id',
        ),
    ]
