# Generated by Django 4.0.4 on 2022-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_remove_action_action_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
