# Generated by Django 4.0.4 on 2022-06-03 20:39

import core.utils
from django.db import migrations, models
import djrichtextfield.models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('body', djrichtextfield.models.RichTextField()),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Name')),
                ('file', models.FileField(blank=True, default='accounts/default-user.png', null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'email_attachments'}), verbose_name='File')),
                ('file_name', models.CharField(help_text='This filename will be used as the attachment name. For example: my_great_ebook.pdf. In case you enter a filename without extension (my_great_ebook), the extension will be added automatically corresponding to the uploaded file.', max_length=32, verbose_name='Send as')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ('-created_at',),
            },
        ),
    ]
