# Generated by Django 4.0.4 on 2022-07-07 09:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_alter_emailattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
