# Generated by Django 4.0.4 on 2022-07-07 12:48

from django.db import migrations
import mails.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_emailtemplate_content_emailtemplate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=mails.models.models.EmailRichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
