# Generated by Django 4.0.4 on 2022-06-02 18:23

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
import djrichtextfield.models
import functools
import phonenumber_field.modelfields
import shop.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=1024, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='BillingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Should be human readable, this will be displayed on checkout.', max_length=255, verbose_name='Name')),
                ('display_name_cs', models.CharField(help_text='Should be human readable, this will be displayed on checkout.', max_length=255, null=True, verbose_name='Name')),
                ('display_name_en', models.CharField(help_text='Should be human readable, this will be displayed on checkout.', max_length=255, null=True, verbose_name='Name')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'payment_method_images'}), verbose_name='Image')),
                ('is_active', models.BooleanField(verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Billing Type',
                'verbose_name_plural': 'Billing Types',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_cs', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GopayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=128, unique=True, verbose_name='Payment ID')),
                ('payment_status', models.CharField(editable=False, max_length=64, verbose_name='Payment Status')),
                ('payment_data', models.JSONField(editable=False, verbose_name='Payment Data')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'GoPay Payment',
                'verbose_name_plural': 'GoPay Payments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, verbose_name='Due Date')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Total Price')),
                ('newsletter_subscribe', models.BooleanField(default=False, verbose_name='Newsletter Subscribe')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('order_number', models.CharField(default=shop.utils.generate_order_number, max_length=25, unique=True, verbose_name='Order Number')),
                ('internal_notification_sent', models.BooleanField(default=False, verbose_name='Internal Notification Sent')),
                ('confirmation_email_sent', models.BooleanField(default=False, verbose_name='Confirmation Email Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_cs', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('amount', models.CharField(blank=True, default='', max_length=32, verbose_name='Amount')),
                ('amount_cs', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Amount')),
                ('amount_en', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Amount')),
                ('description', djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Description')),
                ('description_cs', djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_en', djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('short_description', djrichtextfield.models.RichTextField(blank=True, default='', max_length=125, verbose_name='Short Description')),
                ('short_description_cs', djrichtextfield.models.RichTextField(blank=True, default='', max_length=125, null=True, verbose_name='Short Description')),
                ('short_description_en', djrichtextfield.models.RichTextField(blank=True, default='', max_length=125, null=True, verbose_name='Short Description')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='External URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('image_cs', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.address')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
            },
            bases=('shop.address',),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.order')),
                ('shipping_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Shipping Type')),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': 'Product Orders',
                'ordering': ('-created_at',),
            },
            bases=('shop.order',),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.order')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', "Other / Don't wish to respond")], max_length=125, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('goal', models.CharField(choices=[('reduce', 'Reduce'), ('gain', 'Gain'), ('sustain', 'Sustain')], max_length=125, verbose_name='Goal')),
            ],
            options={
                'verbose_name': 'Service Order',
                'verbose_name_plural': 'Service Orders',
                'ordering': ('-created_at',),
            },
            bases=('shop.order',),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.address')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
            },
            bases=('shop.address',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_cs', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('amount', models.CharField(blank=True, default='', max_length=32, verbose_name='Amount')),
                ('description', djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Description')),
                ('description_cs', djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_en', djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('short_description', djrichtextfield.models.RichTextField(blank=True, default='', max_length=125, verbose_name='Short Description')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='External URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('image_cs', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to=functools.partial(core.utils.user_directory_path, *(), **{'subdir': 'product_images'}), verbose_name='Image')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CZK', max_digits=14, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('ordering',),
            },
        ),
    ]
