# Generated by Django 4.0.4 on 2022-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=1024, verbose_name='Street Address'),
        ),
    ]
