# Generated by Django 4.0.4 on 2022-06-05 11:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_cs',
            field=wagtail.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=125, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_cs',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=125, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=125, null=True, verbose_name='Short Description'),
        ),
    ]
