# Generated by Django 4.0.4 on 2022-06-05 11:41

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.billingaddress', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingaddress', verbose_name='Shipping Address'),
        ),
    ]
