# Generated by Django 4.0.4 on 2022-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cartitem_options_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingtype',
            options={'verbose_name': 'Billing Type', 'verbose_name_plural': 'Billing Types'},
        ),
        migrations.RemoveField(
            model_name='billingtype',
            name='ordering',
        ),
        migrations.AlterField(
            model_name='billingtype',
            name='name',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
