# Generated by Django 4.0.4 on 2022-06-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('shop', '0009_shopsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_enabled', models.BooleanField(default=False, help_text='Enable or disable shop features, like checkout or cart.', verbose_name='Shop Enabled')),
                ('notification_bar_show', models.BooleanField(default=False, verbose_name='Show Notification Bar')),
                ('notification_bar_text', models.CharField(blank=True, max_length=512, null=True, verbose_name='Notification Text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Control Center',
            },
        ),
        migrations.DeleteModel(
            name='ShopSettings',
        ),
    ]
