# Generated by Django 4.0.4 on 2022-06-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_controlcenter_delete_shopsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlCenter',
        ),
    ]
