# Generated by Django 4.0.4 on 2022-07-07 18:20

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_post_save_triggered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_recurrence',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=64, null=True, verbose_name='Payment Recurrence'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CZK', editable=False, max_length=3),
        ),
    ]
