# Generated by Django 4.0.4 on 2022-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_payment_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_recurrence',
            field=models.CharField(blank=True, choices=[('daily', 'Day'), ('weekly', 'Week'), ('monthly', 'Month'), ('yearly', 'Year')], max_length=64, null=True, verbose_name='Payment Recurrence'),
        ),
    ]
