# Generated by Django 4.0.4 on 2022-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_payment_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.CharField(blank=True, default='', help_text='Just an orientation text, if applicable. E.g. 500g', max_length=32, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text="Is the product for sale on another site? Just paste the product's link right here!", verbose_name='External URL'),
        ),
    ]
