# Generated by Django 4.1.1 on 2022-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_amount_alter_product_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Preorder End Date'),
        ),
    ]
