# Generated by Django 4.1.1 on 2022-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preorder_end_date',
            field=models.DateTimeField(blank=True, help_text='If this product is for preorder, you can set the preorder end date here.', null=True, verbose_name='Preorder End Date'),
        ),
    ]
