# Generated by Django 4.1.1 on 2022-09-23 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('shop', '0018_alter_product_preorder_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Variant ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(default='size', max_length=64, verbose_name='Variant Name'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('variant_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Variant ID')),
                ('pcs_in_stock', models.PositiveIntegerField(blank=True, help_text='You can set the ', null=True, verbose_name='Pieces In Stock')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
