# Generated by Django 4.1.1 on 2022-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productvariant_options_productvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='pcs_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pieces In Stock'),
        ),
    ]
