# Generated by Django 4.1.1 on 2022-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_productvariant_pcs_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='product',
            name='variants_name',
            field=models.CharField(default='size', max_length=64, verbose_name='Variants Name'),
        ),
    ]
