# Generated by Django 4.1.1 on 2022-09-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('shop', '0023_cartitem_product_variant'), ('shop', '0024_alter_cartitem_product_variant'), ('shop', '0025_alter_product_related_products'), ('shop', '0026_orderitem_product_variant')]

    dependencies = [
        ('shop', '0022_remove_product_variant_name_product_variants_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant', verbose_name='Product Variant'),
        ),
    ]
