# Generated by Django 4.1.1 on 2022-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_order_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_data',
            field=models.JSONField(verbose_name='Payment Data'),
        ),
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_status',
            field=models.CharField(max_length=64, verbose_name='Payment Status'),
        ),
    ]
