# Generated by Django 4.1.1 on 2022-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_gopaypayment_payment_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_data',
            field=models.JSONField(editable=False, verbose_name='Payment Data'),
        ),
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_id',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='gopaypayment',
            name='payment_status',
            field=models.CharField(editable=False, max_length=64, verbose_name='Payment Status'),
        ),
    ]
