# Generated by Django 4.1.1 on 2022-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='must_be_paid_online',
            field=models.BooleanField(default=False, verbose_name='Product must be paid online'),
        ),
    ]
