# Generated by Django 4.1.1 on 2022-11-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_must_be_paid_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='must_be_paid_online',
            field=models.BooleanField(default=False, verbose_name='Product Must Be Paid Online'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Related products are products of the same type (like t-shirt), but with different properties (like color). ', to='shop.product', verbose_name='Related Products'),
        ),
    ]
