# Generated by Django 4.1.1 on 2022-11-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_product_must_be_paid_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.CharField(max_length=25, verbose_name='Packet ID')),
                ('barcode', models.CharField(max_length=25, verbose_name='Barcode')),
                ('barcode_text', models.CharField(max_length=25, verbose_name='Barcode Text')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status Code')),
                ('status_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Status Name')),
                ('status_display_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Status Display Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Packet',
                'verbose_name_plural': 'Packets',
            },
        ),
    ]
