# Generated by Django 4.1.1 on 2022-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='Turn on this setting for digital products that need no shipping.', verbose_name='Product is Physical'),
        ),
    ]
