# Generated by Django 4.1.1 on 2022-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_product_is_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packeta_point_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Packeta Point ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_point_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Packeta Point Name'),
        ),
    ]
