# Generated by Django 4.1.1 on 2022-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_order_packeta_point_id_order_packeta_point_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.FloatField(blank=True, default=0, verbose_name='Weight in KG'),
        ),
    ]
